services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - staticfiles:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:1qaz2wsx@db:5432/social_media
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - ./image:/app/image
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    command: celery -A alx_project_nexus.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A alx_project_nexus.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env

volumes:
  postgres_data:
  staticfiles:
  image: